# https://taskfile.dev

version: "2"

output: prefixed

tasks:
  default:
    deps:
      - task: test

  test:
    cmds:
      - go test $(go list ./... | grep -v "zxcvbn-go/data")
    desc: Run `go test {package list}`

  lint:
    cmds:
      - golangci-lint run
    desc: Run `golangci-lint run`
