name: Go

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - "**.go"
  pull_request:
    branches:
      - main
    paths:
      - "**.go"

jobs:
  build:
    name: Test and lint and build

    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.16.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        id: go
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: make all
