name: Go

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Test and lint and build

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        id: go

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: make all
